'use strict';
const token=document.querySelector('meta[name="xiapan-token"]').content;
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const labels={windows:'Windows',darwin:'macOS',linux:'Linux',amd64:'x64',arm64:'ARM64'},kinds={models:'模型',packages:'软件包',images:'镜像',drivers:'驱动',runtime:'运行时'};
const names={'startup.inspect':'开机启动项','system.inspect':'系统体检','processes.inspect':'进程内存','network.diagnose':'网络诊断','network.inspect':'网卡信息','drivers.inspect':'网络设备与驱动','tools.catalog':'维护工具集合','tools.launch':'系统工具启动','resources.scan':'盘内资源','models.inspect':'本地模型','tools.install':'便携工具安装','report.create':'保存体检报告','reports.list':'历史报告'};
let session=null,system=null,wallet=null,busy=false,expert=false;
const gib=n=>Number.isFinite(n)?`${(n/1073741824).toFixed(1)} GB`:'未获得',bytes=n=>n>=1073741824?gib(n):`${(n/1048576).toFixed(1)} MB`;
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),4200);}
async function run(action,input={}){const resp=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json','X-Xiapan-Token':token},body:JSON.stringify({action,input})});if(!resp.ok)throw Error(`请求未完成 (${resp.status})`);const r=await resp.json();if(!r.ok)throw Error(r.error||'操作未完成');return r.data;}
function dialog(title,note){const c=$('dialog-content');c.replaceChildren(el('div','XIAPAN / MAINTENANCE','eyebrow'),el('h2',title));if(note)c.append(el('p',note));if(!$('dialog').open)$('dialog').showModal();return c;}
function fail(e){toast(e.message||String(e));}
function button(text,action,fn,cls='primary'){const b=el('button',text,cls);if(action)b.dataset.actionId=action;b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){fail(e);}finally{b.disabled=false;}};return b;}
function detail(parent,data){const d=el('details',undefined,'result-detail');d.append(el('summary','查看真实结果 JSON'),el('pre',JSON.stringify(data,null,2)));parent.append(d);}
function table(parent,head,rows){const t=el('table'),th=el('tr');for(const h of head)th.append(el('th',h));const thead=el('thead');thead.append(th);const tb=el('tbody');for(const row of rows){const tr=el('tr');for(const cell of row)tr.append(el('td',String(cell??'')));tb.append(tr);}t.append(thead,tb);const wrap=el('div',undefined,'table-wrap');wrap.append(t);parent.append(wrap);}
function result(parent,id,d){
 if(id==='system.inspect'){parent.append(el('p',`${labels[d.os]||d.os}${d.os_version?' '+d.os_version:''} ${labels[d.arch]||d.arch} · ${d.cpu_model?d.cpu_model+' · ':''}${d.cpu_threads} 个逻辑处理器`));const stats=el('div',undefined,'stats');stats.append(el('div',`总内存 ${gib(d.memory_bytes)}`),el('div',`可用内存 ${gib(d.available_memory_bytes)}`));parent.append(stats);table(parent,['磁盘','文件系统','可用 / 总量'],(d.volumes||[]).map(v=>[`${v.path} ${v.label||''}`,v.file_system,`${gib(v.free_bytes)} / ${gib(v.size_bytes)}`]));}
 else if(id==='startup.inspect'){table(parent,['名称','来源','状态'],(d.items||[]).map(x=>[x.name,x.source,({enabled:'已启用',disabled:'已禁用',unknown:'待核实'})[x.state]||'待核实']));parent.append(el('p',d.note));for(const w of d.warnings||[])parent.append(el('p',w));const [label,tool]=system?.os==='darwin'?['打开登录项设置','login-items']:['打开任务管理器','task-manager'];parent.append(button(label,'tools.launch',()=>openTool(tool),'secondary'));}
 else if(id==='processes.inspect'){table(parent,['进程','PID','工作集内存'],(d.processes||[]).slice(0,10).map(p=>[p.name,p.pid,bytes(p.memory_bytes)]));parent.append(el('p',d.note||'只读查看，没有结束进程。'));}
 else if(id==='network.diagnose'){parent.append(el('p',`DNS：${(d.checks||[])[0]?.ok?'解析成功':'未成功'} · 云端 HTTPS：${(d.checks||[])[1]?.ok?'可达':'未确认'}`),el('p',d.note||'仅检测，不修改网络配置。'));}
 else if(id==='drivers.inspect'){table(parent,['设备','故障码','驱动 / INF'],(d.devices||[]).map(n=>[n.name,n.error_code,`${n.driver_version||'未读到'} / ${n.inf_name||'未读到'}`]));parent.append(el('p',`本盘驱动文件 ${(d.offline_files||[]).length} 个，尚未自动匹配或安装。`));for(const n of d.devices||[]){const info=el('details');info.append(el('summary',`${n.name||'未知设备'} · 硬件 ID`),el('pre',(n.hardware_ids||[]).join('\n')||'未读到硬件 ID'));parent.append(info);}parent.append(el('p',d.note));}
 else if(id==='tools.catalog'){parent.append(el('p',`系统工具 ${(d.builtin_tools||[]).filter(t=>t.ready).length} 项可用 · 本盘工具 ${(d.portable_tools||[]).filter(t=>t.ready).length} 项已准备`));for(const t of [...(d.portable_tools||[]),...(d.builtin_tools||[])]){parent.append(el('p',`${t.name}${t.version?' '+t.version:''} · ${t.ready?t.source:'未包含当前平台的工具包'}`));if(t.ready)parent.append(button('打开 '+t.name,'tools.launch',()=>openTool(t.id),'secondary'));}parent.append(el('p',d.note));}
 else if(id==='tools.launch'){parent.append(el('p',`${d.name}：${d.note}`));}
 else if(id==='resources.scan'){const stats=el('div',undefined,'stats');for(const [key,name] of Object.entries(kinds)){const count=(d.files||[]).filter(f=>f.kind===key).length;if(count)stats.append(el('div',`${name} ${count} 项`));}parent.append(stats);for(const f of (d.files||[]).slice(0,8)){const row=el('div',undefined,'file-row');row.append(el('span',f.path),el('span',bytes(f.size_bytes)));parent.append(row);}if(!(d.files||[]).length)parent.append(el('p','没有发现资源文件；请按标准目录提前放入。'));}
 else if(id==='models.inspect'){parent.append(el('p',d.ready?'本地模型服务可用':'本地模型服务未启动'),el('p',d.advice));}
 else if(id==='tools.install'){parent.append(el('p','文件校验与实际启动验证已通过。'));}
 else if(id==='report.create'){parent.append(el('p','新的报告已保存到本盘 data/reports。'));}
 else if(id==='reports.list'){parent.append(el('p',`本盘有 ${(d||[]).length} 份体检报告。`));}
 detail(parent,d);
}
function render(){if(!session)return;$('task-title').textContent=session.title;$('welcome').classList.toggle('hidden',session.messages.length>0);const box=$('messages');box.replaceChildren();const traces=[];
 for(const m of session.messages){const c=el('article',undefined,`message ${m.role}`);c.dataset.messageId=m.id;
  if(m.role==='user'||m.role==='assistant'||m.role==='notice'){c.append(el('div',m.role==='user'?'你':m.role==='notice'?'提示':'虾盘','message-label'),el('div',m.text,'message-text'));}
  else if(m.role==='action'){c.className='action-card';c.append(el('div','✓ '+(names[m.action]||m.action),'action-heading'));result(c,m.action,m.data);traces.push(m);}
  else if(m.role==='proposal'){c.className='proposal-card';c.append(el('div',m.completed?'✓ 已完成':'等待你确认','action-heading'),el('p',m.text));if(!m.completed&&session.pending.some(p=>p.id===m.proposal_id)){const b=button('确认执行',m.action,()=>confirm(m.proposal_id));b.disabled=busy;c.append(b);} }
  box.append(c);
 }
 const trace=$('trace-content');trace.replaceChildren();for(const m of traces){const c=el('details',undefined,'trace-item');c.append(el('summary',m.action),el('pre',JSON.stringify(m.data,null,2)));trace.append(c);}$('trace-count').textContent=`${traces.length} actions`;box.lastElementChild?.scrollIntoView({block:'nearest'});
}
function setBusy(value,text='● 正在处理当前任务…'){busy=value;$('send').disabled=value;$('new-chat').disabled=value;$('question').disabled=value;$('engine-select').disabled=value;$('cloud-model').disabled=value;$('busy-status').classList.toggle('hidden',!value);$('busy-status').textContent=text;for(const b of document.querySelectorAll('.proposal-card button'))b.disabled=value;}
async function listSessions(){const rows=await run('chat.list'),c=$('session-list');c.replaceChildren();for(const row of rows){const b=el('button',row.title,'session-item');if(session&&row.id===session.id)b.classList.add('active');b.onclick=async()=>{if(busy)return;try{session=await run('chat.read',{session_id:row.id});showView('chat');render();await listSessions();}catch(e){fail(e);}};c.append(b);}return rows;}
async function newChat(){if(busy)return;session=await run('chat.start');showView('chat');render();await listSessions();$('question').focus();}
async function send(message){if(busy||!message.trim())return;if(!session)await newChat();showView('chat');setBusy(true,$('engine-select').value==='local'?'● 本盘离线 AI：校验与启动可能需要几十秒…':'● 正在检测与回答…');
 const progressTimer=setInterval(async()=>{try{const p=await run('chat.progress',{session_id:session.id});if(p){const saved=session;session=p;render();session=saved;}}catch{}},800);
 const local=el('article',undefined,'message user');local.append(el('div','你','message-label'),el('div',message,'message-text'));$('messages').append(local);$('welcome').classList.add('hidden');local.scrollIntoView({block:'nearest'});$('question').value='';
 try{session=await run('chat.send',{session_id:session.id,expected_version:session.version,message,engine:$('engine-select').value,model:$('cloud-model').value});render();await listSessions();}catch(e){fail(e);try{session=await run('chat.read',{session_id:session.id});render();}catch{} }finally{clearInterval(progressTimer);setBusy(false);$('question').focus();}
}
async function confirm(proposalID){if(busy)return;setBusy(true,'● 正在执行已确认的操作并验证…');try{session=await run('chat.confirm',{session_id:session.id,expected_version:session.version,proposal_id:proposalID,confirmed:true});render();}finally{setBusy(false);}}
function engineNote(){const value=$('engine-select').value;$('cloud-model').classList.add('hidden');$('engine-note').textContent=value==='pico'?`${modelSettings?.model||'选择模型'} · ${modelSettings?.source==='custom'?'自带 API':'虾盘云'} · 设置与对话随盘保存`:value==='local'?'本盘离线模型':'本地工具 · 无需模型';}
async function openTool(id){if(busy)return;const d=await run('tools.launch',{tool_id:id,confirmed:true});toast(d.name+' 已提交启动');}
async function inspect(){system=await run('system.inspect');$('computer-tag').textContent=`${labels[system.os]||system.os} ${labels[system.arch]||system.arch} · ${gib(system.memory_bytes)}`;$('drive-status').textContent=system.portable_root;$('drive-status').title=system.portable_root;}
function walletMini(){if(!wallet)return;$('wallet-mini-note').textContent=wallet.ready?(wallet.available_tokens!==undefined?`余额 ${Number(wallet.available_tokens).toLocaleString()} token`:'钱包已保存 · 余额待查询'):'联网获取 · 或填入已有钱包';}
async function models(){try{const d=await run('cloud.models'),old=$('cloud-model').value;$('cloud-model').replaceChildren();for(const m of d.models)$('cloud-model').append(new Option(m,m));$('cloud-model').value=d.models.includes(old)?old:d.selected;}catch{$('cloud-model').replaceChildren(new Option('模型列表暂不可用',''));}}
async function walletView(){if(!wallet){try{wallet=await run('wallet.ensure');walletMini();}catch(e){wallet={ready:false,note:e.message};}}
 const c=dialog('设备钱包','免注册，凭证就是钱包。请备份凭证，随盘丢失也会失去访问入口。');c.append(el('div',wallet.ready?wallet.masked_key:'尚未获取钱包','wallet-key'),el('div',wallet.available_tokens!==undefined?`${Number(wallet.available_tokens).toLocaleString()} token`:'余额未获得','wallet-amount'),el('p',wallet.note||''));
 const row=el('div',undefined,'button-row');row.append(button('充值 ↗','wallet.recharge',async()=>{await run('wallet.recharge');toast('已在系统浏览器打开充值页，请自行选择与付款');}),button('刷新余额','wallet.refresh',async()=>{wallet=await run(wallet.ready?'wallet.refresh':'wallet.ensure');walletMini();await walletView();await models();},'secondary'));if(wallet.ready)row.append(button('备份凭证','wallet.copy',async()=>{const d=await run('wallet.copy',{confirmed:true});try{await navigator.clipboard.writeText(d.api_key);toast('凭证已复制，请保存到你自己的安全位置');}catch{const reveal=el('input');reveal.value=d.api_key;reveal.readOnly=true;reveal.type='text';reveal.setAttribute('aria-label','待备份的钱包凭证');c.append(reveal);reveal.select();toast('请手动复制；关闭窗口后不再展示');}},'secondary'));c.append(row);
 const adopt=el('details',undefined,'wallet-adopt');adopt.append(el('summary','填入已有钱包'));const input=el('input');input.type='password';input.autocomplete='off';input.placeholder='粘贴 sk- 开头的钱包凭证';input.setAttribute('aria-label','已有钱包凭证');adopt.append(input,button('验证并使用','wallet.adopt',async()=>{wallet=await run('wallet.adopt',{api_key:input.value});input.value='';walletMini();await walletView();await models();}));c.append(adopt);
 if(wallet.ready){const danger=el('details',undefined,'wallet-danger');danger.append(el('summary','钱包管理'));danger.append(button('换一把凭证','wallet.rotate',async()=>{const p=dialog('确认换一把凭证','余额保留在同一钱包，完成后旧凭证会失效。请重新备份新凭证。');p.append(button('确认换一把','wallet.rotate',async()=>{wallet=await run('wallet.rotate',{confirmed:true});walletMini();await walletView();}));},'text-button'));danger.append(button('从本盘移除钱包','wallet.reset',async()=>{const p=dialog('移除本盘钱包','旧钱包和余额保留在服务端。创建的新钱包不会带入旧余额。');const label=el('label'),check=el('input');check.type='checkbox';label.append(check,document.createTextNode(' 我已备份旧钱包凭证'));p.append(label,button('确认移除','wallet.reset',async()=>{if(!check.checked)throw Error('请先备份并勾选确认');wallet=await run('wallet.reset',{confirmed:true,backed_up:true});walletMini();await walletView();}));},'text-button'));c.append(danger);}
}
async function offline(){const d=await run('models.inspect'),c=dialog('断网急救','先恢复联网通道。下面的本地工具不需要云端 AI 或钱包额度。');const row=el('div',undefined,'button-row');for(const [label,cmd,action] of [['识别网卡与驱动','/驱动','drivers.inspect'],['检查网络','/网络','network.diagnose'],['查看工具集合','/工具','tools.catalog']])row.append(button(label,action,async()=>{$('dialog').close();await send(cmd);},'secondary'));c.append(row,el('p','试试有线连接或手机 USB 共享网络。需要驱动时，在有网电脑从整机/网卡厂商官网按硬件 ID 准备对应系统的包，放入 drivers/；当前不会自动匹配或安装。'),el('p',d.advice));if(d.bundled)c.append(button(d.ready?'使用本盘离线 AI':'启动并使用本盘离线 AI','models.start',async()=>{if(!d.ready)await run('models.start',{confirmed:true});$('engine-select').value='local';engineNote();$('dialog').close();showView('chat');toast('已选择本盘离线 AI');}));c.append(button('使用维护向导','chat.send',async()=>{$('engine-select').value='guide';engineNote();$('dialog').close();showView('chat');},'secondary'));if(d.ready)c.append(button('停止本盘启动的模型','models.stop',async()=>{await run('models.stop');await offline();},'text-button'));detail(c,d);}
async function resources(){const d=await run('resources.scan'),c=$('resources-content');c.replaceChildren();for(const [kind,name] of Object.entries(kinds)){const files=d.files.filter(f=>f.kind===kind);if(!files.length)continue;const card=el('article',undefined,'resource-group');card.append(el('h3',`${name} · ${files.length} 项`));for(const f of files){const row=el('div',undefined,'file-row');row.append(el('span',f.path),el('span',bytes(f.size_bytes)));card.append(row);}if(!files.length)card.append(el('p',`请把${name}文件提前放进 ${kind}/ 目录。`));c.append(card);}for(const w of d.warnings)c.append(el('p',w));}
async function toolCollection(){renderToolLibrary(await run('tools.catalog'));}
function showView(view){document.body.classList.remove('history-open');document.querySelector('.sidebar').inert=true;$('history-open').setAttribute('aria-expanded','false');for(const n of document.querySelectorAll('.view'))n.classList.toggle('hidden',n.id!==`${view}-view`);for(const b of document.querySelectorAll('.nav-item'))b.classList.toggle('active',b.dataset.view===view);if(view==='resources')resources().catch(fail);if(view==='tools')toolCollection().catch(fail);}
const commands=[['/启动项','开机自启清单与状态'],['/体检','系统与内存、磁盘'],['/进程','进程工作集内存'],['/网络','网卡、DNS、云端 HTTPS'],['/驱动','硬件 ID、故障码、盘内驱动'],['/工具','可打开的系统工具与资源集合'],['/资源','盘内软件、模型、镜像'],['/模型','本地模型服务状态'],['/安装','便携体检工具 · 确认后安装'],['/报告','新的体检报告 · 确认后保存'],['/救援','无法启动时的准备方案']];
for(const [cmd,description] of commands){const b=el('button',undefined,'palette-command');b.append(el('code',cmd),el('span',description));b.onclick=()=>{$('palette').close();send(cmd).catch(fail);};$('palette-commands').append(b);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view)showView(b.dataset.view);if(b.dataset.prompt){$('question').value=b.dataset.prompt;$('question').focus();}if(b.dataset.command)send(b.dataset.command).catch(fail);});
$('chat-form').onsubmit=e=>{e.preventDefault();send($('question').value).catch(fail);};$('question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send($('question').value).catch(fail);}};
$('engine-select').onchange=engineNote;$('model-settings').onclick=()=>modelSettingsView().catch(fail);$('history-open').onclick=()=>{const open=document.body.classList.toggle('history-open');$('history-open').setAttribute('aria-expanded',String(open));document.querySelector('.sidebar').inert=!open;};$('new-chat').onclick=()=>newChat().catch(fail);$('expert-toggle').onclick=()=>{expert=!expert;$('trace-panel').classList.toggle('hidden',!expert);$('expert-toggle').textContent=expert?'关闭专业模式':'专业模式';};$('wallet-open').onclick=()=>walletView().catch(fail);$('local-ai-open').onclick=()=>offline().catch(fail);$('dialog-close').onclick=()=>{$('dialog').close();$('dialog-content').replaceChildren();};$('dialog').addEventListener('close',()=>{$('dialog-content').replaceChildren();});$('palette-open').onclick=()=>$('palette').showModal();$('palette-close').onclick=()=>$('palette').close();
$('reports-open').onclick=async()=>{try{const d=await run('reports.list'),c=dialog('本盘维护记录',`共 ${d.length} 份报告。`);for(const r of d){const a=el('article',undefined,'action-card');a.append(el('h3',new Date(r.created_at).toLocaleString('zh-CN')));detail(a,r);c.append(a);}}catch(e){fail(e);}};
$('skills-open').onclick=async()=>{try{const r=await (await fetch('/api/skills')).json();if(!r.ok)throw Error(r.error);const c=dialog('维护技能','技能规定维护步骤，执行能力由真实工具提供。');for(const s of r.data){const d=el('details',undefined,'skill-card');d.append(el('summary',s.id),el('pre',s.content));c.append(d);}}catch(e){fail(e);}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('palette').showModal();}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();newChat().catch(fail);}});
if(/Mac/i.test(navigator.platform))for(const k of document.querySelectorAll('kbd'))k.textContent=k.textContent.replace('Ctrl','⌘');
$('quit').onclick=async()=>{try{const r=await fetch('/api/quit',{method:'POST',headers:{'X-Xiapan-Token':token}});if(!r.ok)throw Error('退出未完成');dialog('虾盘已退出','本次启动的模型服务已停止。可以关闭页面，然后安全移除 U 盘。');}catch(e){fail(e);}};
(async()=>{try{await loadSettings();}catch(e){fail(e);}engineNote();await inspect();const rows=await listSessions();session=rows.length?await run('chat.read',{session_id:rows[0].id}):await run('chat.start');render();await listSessions();})().catch(fail);
// Wallet creation is requested explicitly from model settings or the wallet panel.
